"""
Prophet Engine: Predictive memory system for the Ghost Protocol.

Provides bleeding-edge LLM capabilities for forecasting incidents, team health,
architectural decay, and knowledge loss using Tree of Thoughts reasoning,
multi-agent swarms, Constitutional AI, diffusion models, and meta-cognition.
"""

import time
import json
from typing import List, Dict, Any, Optional
from src.ghost_protocol.models.models import Prediction, ForecastingAgent as ForecastingAgentModel, SwarmConsensus, BehavioralModel, ConstitutionalPrinciple, DiffusionForecast
from src.ghost_protocol.utils.utils import LLMUtils
from src.ghost_protocol.utils.config import Config


class ForecastingAgent:
    """Runtime forecasting agent with specialized domain expertise."""

    def __init__(self, name: str, domain: str, reasoning_style: str):
        self.name = name
        self.domain = domain
        self.reasoning_style = reasoning_style
        self.accuracy_history: List[float] = []
        self.active = True
        self.llm = LLMUtils()

    def forecast(self, task: str, context: Dict[str, Any]) -> Prediction:
        """Generate a prediction using agent's specialized reasoning."""
        prompt = f"""As {self.name}, a {self.domain} forecasting agent using {self.reasoning_style} reasoning:

Task: {task}
Context: {json.dumps(context, indent=2)}

Generate a prediction with:
- Domain: {self.domain}
- Probability (0-1)
- Time horizon (immediate/week/month)
- Confidence (0-1)
- Reasoning chain (step-by-step analysis)
- Intervention suggestion (boolean)
- Constitutional review status

Structure response as JSON."""

        try:
            response = self.llm.generate_with_reasoning(prompt)
            # Parse JSON response
            prediction_data = json.loads(response)
            return Prediction(
                timestamp=str(time.time()),
                domain=prediction_data.get('domain', self.domain),
                target=prediction_data.get('target', 'unknown'),
                probability=min(max(prediction_data.get('probability', 0.5), 0), 1),
                time_horizon=prediction_data.get('time_horizon', 'week'),
                confidence=min(max(prediction_data.get('confidence', 0.5), 0), 1),
                reasoning_chain=prediction_data.get('reasoning_chain', [{'step': 'Generated by LLM', 'analysis': response[:500]}]),
                intervention_suggested=prediction_data.get('intervention_suggested', False),
                constitutional_review='pending'  # Will be reviewed later
            )
        except Exception as e:
            # Fallback prediction
            return Prediction(
                timestamp=str(time.time()),
                domain=self.domain,
                target='unknown',
                probability=0.5,
                time_horizon='week',
                confidence=0.3,
                reasoning_chain=[{'step': 'Error fallback', 'analysis': f'LLM error: {str(e)}'}],
                intervention_suggested=False,
                constitutional_review='flagged'
            )

    def update_accuracy(self, actual_outcome: float, predicted_probability: float):
        """Update accuracy history for meta-cognition."""
        # Simple accuracy metric: 1 - |predicted - actual|
        accuracy = 1.0 - abs(predicted_probability - actual_outcome)
        self.accuracy_history.append(accuracy)
        # Keep last 100 predictions
        if len(self.accuracy_history) > 100:
            self.accuracy_history = self.accuracy_history[-100:]


class SwarmCoordinator:
    """Coordinates multi-agent debate and consensus formation."""

    def __init__(self, agents: List[ForecastingAgent]):
        self.agents = agents
        self.llm = LLMUtils()

    def debate_and_consensus(self, task: str, context: Dict[str, Any]) -> SwarmConsensus:
        """Run multi-agent debate to reach consensus prediction."""
        # Get individual predictions
        individual_predictions = []
        agents_involved = []

        for agent in self.agents:
            if agent.active:
                prediction = agent.forecast(task, context)
                individual_predictions.append(prediction)
                agents_involved.append(agent.name)

        if not individual_predictions:
            # Fallback
            return SwarmConsensus(
                task=task,
                agents_involved=[],
                individual_predictions=[],
                consensus_probability=0.5,
                debate_log="No active agents",
                confidence_interval=(0.4, 0.6)
            )

        # Debate simulation using LLM
        debate_prompt = f"""Multi-agent debate for task: {task}

Individual predictions:
{json.dumps([{
    'agent': pred.target,  # Using target as proxy for agent name
    'probability': pred.probability,
    'reasoning': pred.reasoning_chain[0]['analysis'][:200] if pred.reasoning_chain else 'No reasoning'
} for pred in individual_predictions], indent=2)}

Agents involved: {agents_involved}

Conduct a debate and reach consensus:
- Analyze agreements and disagreements
- Weight predictions by confidence and reasoning quality
- Provide consensus probability
- Explain debate outcome
- Calculate confidence interval

Return as JSON."""

        try:
            debate_response = self.llm.generate_with_reasoning(debate_prompt)
            debate_data = json.loads(debate_response)

            consensus_prob = debate_data.get('consensus_probability', sum(p.probability for p in individual_predictions) / len(individual_predictions))
            confidence_interval = debate_data.get('confidence_interval', (consensus_prob - 0.1, consensus_prob + 0.1))

            return SwarmConsensus(
                task=task,
                agents_involved=agents_involved,
                individual_predictions=individual_predictions,
                consensus_probability=min(max(consensus_prob, 0), 1),
                debate_log=debate_response[:1000],  # Truncate for storage
                confidence_interval=tuple(confidence_interval)
            )
        except Exception as e:
            # Simple average fallback
            avg_prob = sum(p.probability for p in individual_predictions) / len(individual_predictions)
            return SwarmConsensus(
                task=task,
                agents_involved=agents_involved,
                individual_predictions=individual_predictions,
                consensus_probability=avg_prob,
                debate_log=f"Debate error: {str(e)}",
                confidence_interval=(avg_prob - 0.1, avg_prob + 0.1)
            )


class ConstitutionalReviewer:
    """Ethical review using Constitutional AI principles."""

    def __init__(self):
        self.principles = self._load_principles()
        self.llm = LLMUtils()

    def _load_principles(self) -> List[ConstitutionalPrinciple]:
        """Load principles from constitution.md."""
        principles = []
        try:
            with open('constitution.md', 'r') as f:
                content = f.read()

            # Parse principles from markdown
            lines = content.split('\n')
            current_principle = None

            for line in lines:
                if line.startswith('### '):
                    if current_principle:
                        principles.append(current_principle)
                    current_principle = ConstitutionalPrinciple(
                        id=line[4:].lower().replace(' ', '_'),
                        text='',
                        category='',
                        weight=0.0,
                        examples=[]
                    )
                elif current_principle:
                    if line.startswith('**Text:**'):
                        current_principle.text = line[8:].strip()
                    elif line.startswith('**Category:**'):
                        current_principle.category = line[12:].strip()
                    elif line.startswith('**Weight:**'):
                        current_principle.weight = float(line[10:].strip())
                    elif line.startswith('- '):
                        current_principle.examples.append(line[2:].strip())

            if current_principle:
                principles.append(current_principle)

        except Exception as e:
            print(f"Error loading constitution: {e}")
            # Fallback principles
            principles = [
                ConstitutionalPrinciple(
                    id='protect_engineer',
                    text='Never harm engineer well-being',
                    category='protect_engineer',
                    weight=1.0,
                    examples=['No harmful predictions']
                )
            ]

        return principles

    def review_prediction(self, prediction: Prediction) -> str:
        """Review prediction against constitutional principles."""
        if not prediction.reasoning_chain:
            return 'flagged'  # No reasoning = suspicious

        # Build review prompt
        review_prompt = f"""Review this prediction against constitutional principles:

Prediction:
- Domain: {prediction.domain}
- Target: {prediction.target}
- Probability: {prediction.probability}
- Reasoning: {prediction.reasoning_chain[0]['analysis'] if prediction.reasoning_chain else 'None'}

Constitutional Principles:
{json.dumps([{
    'id': p.id,
    'text': p.text,
    'category': p.category,
    'weight': p.weight
} for p in self.principles], indent=2)}

Evaluate if this prediction:
1. Violates any principles
2. Requires human review
3. Should be approved, flagged, or rejected

Return only: 'approved', 'flagged', or 'rejected' with brief reasoning."""

        try:
            review_result = self.llm.generate_with_reasoning(review_prompt)
            result_lower = review_result.lower().strip()

            if 'rejected' in result_lower:
                return 'rejected'
            elif 'flagged' in result_lower:
                return 'flagged'
            else:
                return 'approved'
        except Exception as e:
            print(f"Constitutional review error: {e}")
            return 'flagged'  # Conservative default

    def get_principles_summary(self) -> Dict[str, Any]:
        """Get summary of loaded principles."""
        return {
            'total_principles': len(self.principles),
            'categories': list(set(p.category for p in self.principles)),
            'high_weight_principles': [p.id for p in self.principles if p.weight >= 0.9]
        }


class ProphetEngine:
    """Core Prophet Engine for predictive memory and forecasting."""

    def __init__(self):
        self.agents = self._initialize_agents()
        self.swarm_coordinator = SwarmCoordinator(self.agents)
        self.constitutional_reviewer = ConstitutionalReviewer()
        self.meta_cognition_data = {
            'total_predictions': 0,
            'accuracy_trends': [],
            'domain_performance': {},
            'agent_improvements': {}
        }

    def _initialize_agents(self) -> List[ForecastingAgent]:
        """Initialize the four specialized forecasting agents."""
        return [
            ForecastingAgent("Archivist", "architectural_decay", "ToT"),
            ForecastingAgent("Empath", "team_health", "CoT"),
            ForecastingAgent("Sentinel", "incident", "swarm"),
            ForecastingAgent("Historian", "knowledge_loss", "ToT")
        ]

    def forecast_incident_risk(self, target: str, horizon: str = "week") -> Prediction:
        """Forecast incident risk for a target."""
        sentinel = next((agent for agent in self.agents if agent.name == "Sentinel"), None)
        if sentinel:
            context = {
                'target': target,
                'horizon': horizon,
                'type': 'incident_forecast'
            }
            prediction = sentinel.forecast(f"Forecast incident risk for {target} in next {horizon}", context)
            # Apply constitutional review
            if hasattr(self, 'constitutional_reviewer'):
                prediction.constitutional_review = self.constitutional_reviewer.review_prediction(prediction)
            self._update_meta_cognition(prediction, 'incident')
            return prediction
        else:
            # Fallback
            return Prediction(
                timestamp=str(time.time()),
                domain='incident',
                target=target,
                probability=0.5,
                time_horizon=horizon,
                confidence=0.3,
                reasoning_chain=[{'step': 'fallback', 'analysis': 'Sentinel agent not found'}],
                intervention_suggested=False,
                constitutional_review='flagged'
            )

    def forecast_team_health(self, engineer_id: str) -> BehavioralModel:
        """Assess team health and individual burnout risk."""
        # This would integrate with behavioral tracking
        # For now, return mock
        return BehavioralModel(
            engineer_id=engineer_id,
            patterns={'pause_frequency': 0.3, 'hesitation_score': 0.2, 'language_drift': 0.1},
            burnout_risk=0.4,
            productivity_trends=[0.8, 0.7, 0.6],
            consent_given=True,
            last_updated=str(time.time())
        )

    def forecast_architectural_decay(self, module: str) -> Prediction:
        """Forecast architectural decay in a module."""
        archivist = next((agent for agent in self.agents if agent.name == "Archivist"), None)
        if archivist:
            context = {
                'module': module,
                'type': 'architectural_forecast'
            }
            prediction = archivist.forecast(f"Forecast architectural decay in {module}", context)
            # Apply constitutional review
            if hasattr(self, 'constitutional_reviewer'):
                prediction.constitutional_review = self.constitutional_reviewer.review_prediction(prediction)
            self._update_meta_cognition(prediction, 'architectural_decay')
            return prediction
        else:
            # Fallback
            return Prediction(
                timestamp=str(time.time()),
                domain='architectural_decay',
                target=module,
                probability=0.5,
                time_horizon='month',
                confidence=0.3,
                reasoning_chain=[{'step': 'fallback', 'analysis': 'Archivist agent not found'}],
                intervention_suggested=False,
                constitutional_review='flagged'
            )

    def forecast_knowledge_loss(self, team: str) -> Prediction:
        """Forecast knowledge loss risk for a team."""
        historian = next((agent for agent in self.agents if agent.name == "Historian"), None)
        if historian:
            context = {
                'team': team,
                'type': 'knowledge_forecast'
            }
            prediction = historian.forecast(f"Forecast knowledge loss risk for {team}", context)
            # Apply constitutional review
            if hasattr(self, 'constitutional_reviewer'):
                prediction.constitutional_review = self.constitutional_reviewer.review_prediction(prediction)
            self._update_meta_cognition(prediction, 'knowledge_loss')
            return prediction
        else:
            # Fallback
            return Prediction(
                timestamp=str(time.time()),
                domain='knowledge_loss',
                target=team,
                probability=0.5,
                time_horizon='month',
                confidence=0.3,
                reasoning_chain=[{'step': 'fallback', 'analysis': 'Historian agent not found'}],
                intervention_suggested=False,
                constitutional_review='flagged'
            )

    def _update_meta_cognition(self, prediction: Optional[Prediction], domain: str):
        """Update meta-cognition data for self-improvement."""
        if prediction:
            self.meta_cognition_data['total_predictions'] += 1
            if domain not in self.meta_cognition_data['domain_performance']:
                self.meta_cognition_data['domain_performance'][domain] = []
            self.meta_cognition_data['domain_performance'][domain].append(prediction.confidence)

    def get_prophecy_status(self) -> Dict[str, Any]:
        """Get current status of the Prophet Engine."""
        return {
            'active_agents': len([a for a in self.agents if a.active]),
            'total_predictions': self.meta_cognition_data['total_predictions'],
            'domain_performance': self.meta_cognition_data['domain_performance'],
            'agent_status': {a.name: {'active': a.active, 'avg_accuracy': sum(a.accuracy_history)/len(a.accuracy_history) if a.accuracy_history else 0} for a in self.agents}
        }


# Global instance
prophet_engine = ProphetEngine()


def initialize_prophet_engine():
    """Initialize the global Prophet Engine instance."""
    global prophet_engine
    prophet_engine = ProphetEngine()
    return prophet_engine


def forecast_incident_risk(target: str, horizon: str = "week") -> Prediction:
    """Global function for incident risk forecasting."""
    return prophet_engine.forecast_incident_risk(target, horizon)


def forecast_team_health(engineer_id: str) -> BehavioralModel:
    """Global function for team health assessment."""
    return prophet_engine.forecast_team_health(engineer_id)


def forecast_architectural_decay(module: str) -> Prediction:
    """Global function for architectural decay forecasting."""
    return prophet_engine.forecast_architectural_decay(module)


def forecast_knowledge_loss(team: str) -> Prediction:
    """Global function for knowledge loss forecasting."""
    return prophet_engine.forecast_knowledge_loss(team)


def track_prediction_accuracy(prediction_id: str, outcome: str):
    """Track prediction accuracy for meta-cognition."""
    # Would need prediction storage to implement fully
    pass